package de.ShadwGHG.claim;

import de.ShadwGHG.claim.ClaimManager;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.UUID;

public class claim extends JavaPlugin {

    private ClaimManager claimManager;

    public claim(UUID playerUUID) {
    }

    @Override
    public void onEnable() {
        getLogger().info("ClaimPlugin wurde aktiviert.");
        claimManager = new ClaimManager();

        Bukkit.getPluginManager().registerEvents(new ClaimListener(this), this);

        getCommand("claim").setExecutor(new ClaimCommand(this));
        getCommand("addmember").setExecutor(new AddMemberCommand(this));
    }

    @Override
    public void onDisable() {
        getLogger().info("ClaimPlugin wurde deaktiviert.");
    }

    public ClaimManager getClaimManager() {
        return claimManager;
    }
}
